---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - catalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - catalogs/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - catalogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - globalvariables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - globalvariables/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - globalvariables/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqls/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - storagevaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - storagevaults/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - storagevaults/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - workloadgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - workloadgroups/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - workloadgroups/status
  verbs:
  - get
  - patch
  - update
