# Default values for manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: ~
port: 9030
authSecret: ~
users: []
  # - username: test_user
  #   passwordSecretRef:
  #     name: user-credentials
  #     key: test_user
  #   grants:
  #     - privileges:
  #         - SELECT
  #         - ALTER
  #         - INSERT
  #       target: TABLE db1.tbl1
  #     - privileges:
  #         - SELECT
  #       target: ALL TABLES IN DATABASE db1
  #     - privileges:
  #         - SELECT
  #       target: ALL TABLES IN ALL DATABASES
  #     - privileges:
  #         - USAGE
  #       target: RESOURCE 'test_resource'

storageVaults: []
  # - name: aws_s3_vault
  #   properties:
  #     type: S3
  #     s3.endpoint: s3.us-east-1.amazonaws.com
  #     s3.region: us-east-1
  #     s3.root.path: s3_vault_prefix
  #     s3.bucket: my-bucket
  #     provider: S3
  #     use_path_style: false
  #   propertiesSecret: aws-s3-vault-secret
  #   isDefault: true
