---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "doris-resource-manager.name" . }}-user-credentials
  namespace: {{ template "doris-resource-manager.namespace" . }}
  labels:
    app.kubernetes.io/name: doris-resource-manager
    app.kubernetes.io/instance: {{ template "doris-resource-manager.name" . }}
    {{- if .Values.secretLabels }}
    {{- toYaml .Values.secretLabels | nindent 4}}
    {{- end }}
  {{- if .Values.secretAnnotations }}
  annotations: {{- toYaml .Values.secretAnnotations | nindent 4}}
  {{- end }}
type: Opaque
stringData:
  {{- range .Values.users }}
  {{ .username | quote }}: {{ .password | quote }}
  {{- end }}
